[package]
name = "zn_multiplication"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "1.3.0" }
indexmap = { version = "2.14.0", features = ["serde"] }
rand = { version = "0.9.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tfhe = { version = "~1.1.3", features = ["integer"] }

[[bin]]
name = "client_key_generation"

[[bin]]
name = "client_preprocess_input"

[[bin]]
name = "client_encode_encrypt_input"

[[bin]]
name = "server_encrypted_compute"

[[bin]]
name = "client_decrypt_decode"

[[bin]]
name = "client_postprocess"
